services:
  lb:
    image: haproxy:alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sock:/run/sock
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30m"

  api1:
    image: lucasgoveia/rinha-2026:latest
    environment:
      SOCK: /run/sock/api1.sock
    volumes:
      - sock:/run/sock
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160m"

  api2:
    image: lucasgoveia/rinha-2026:latest
    environment:
      SOCK: /run/sock/api2.sock
    volumes:
      - sock:/run/sock
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160m"

networks:
  rinha:
    driver: bridge

volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=0,gid=0
