services:
  api1: &api
    image: lucasgoveia/rinha-2026:c56ef01
    environment:
      - SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    <<: *api
    environment:
      - SOCK=/run/sock/api2.sock

  lb:
    image: haproxy:alpine
    restart: always
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  sock:
