services:
  lb:
    build: ./lb
    volumes:
      - sock:/run/sock
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - rinha
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_syncookies=0
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30m"

  api1:
    build:
      context: ..
      dockerfile: rinha-2026/Dockerfile
    environment:
      SOCK: /run/sock/api1.sock
      FAST_NPROBE: "4"
    volumes:
      - sock:/run/sock
    networks:
      - rinha
    restart: always
    cap_add:
      - IPC_LOCK
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160m"

  api2:
    build:
      context: ..
      dockerfile: rinha-2026/Dockerfile
    environment:
      SOCK: /run/sock/api2.sock
      FAST_NPROBE: "4"
    volumes:
      - sock:/run/sock
    networks:
      - rinha
    restart: always
    cap_add:
      - IPC_LOCK
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160m"

networks:
  rinha:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "65535"

volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=0,gid=0
