use flate2::read::GzDecoder;
use serde::Deserialize;
use std::cell::UnsafeCell;
use std::ffi::CString;

const DIMS: usize = 14;
const DIMS_PAD: usize = 16;
const PAIRS: usize = 7;
const BLOCK: usize = 8;
const NUM_CLUSTERS: usize = 4096;
const KMEANS_ITERS: usize = 30;
const K: usize = 5;
const SCALE: f32 = 10000.0;

const FULL_NPROBE: usize = 24;
const FAST_NPROBE: usize = FULL_NPROBE;

// Per-count fast→full escalation thresholds. Index by fraud_count after fast pass.
// If worst_dist >= FAST_T[count], rerun with FULL_NPROBE.
// Generated by bin/tune against /tmp/rinha-index.bin.
const FAST_T: [i64; 6] = [
    10_877_135, // count=0
    12_198_590, // count=1
    11_890_860, // count=2
    11_945_090, // count=3
    12_111_004, // count=4
    12_204_271, // count=5
];

const MAGIC: &[u8; 8] = b"RINHA005";

#[derive(Deserialize)]
struct RefEntry {
    vector: [f32; DIMS],
    label: String,
}

fn quantize_vec(v: &[f32; DIMS]) -> [i16; DIMS] {
    v.map(|x| (x * SCALE).round().clamp(-SCALE, SCALE) as i16)
}

#[inline(always)]
fn l2sq_i16(a: &[i16; DIMS], b: &[i16; DIMS]) -> i32 {
    let mut s = 0i32;
    for i in 0..DIMS {
        let d = a[i] as i32 - b[i] as i32;
        s += d * d;
    }
    s
}

// ---------- Top-5 max-heap (i64 dist, u8 fraud bit) ----------

struct Top5 {
    dist: [i64; K],
    fraud: [u8; K],
    count: usize,
}

impl Top5 {
    fn new() -> Self {
        Self { dist: [i64::MAX; K], fraud: [0; K], count: 0 }
    }
    fn full(&self) -> bool { self.count == K }
    fn worst(&self) -> i64 { self.dist[0] }
    fn push(&mut self, d: i64, fraud_bit: u8) {
        if self.count < K {
            let pos = self.count;
            self.dist[pos] = d;
            self.fraud[pos] = fraud_bit;
            self.count += 1;
            self.sift_up(pos);
        } else if d < self.dist[0] {
            self.dist[0] = d;
            self.fraud[0] = fraud_bit;
            self.sift_down(0);
        }
    }
    fn sift_up(&mut self, mut pos: usize) {
        while pos > 0 {
            let parent = (pos - 1) / 2;
            if self.dist[parent] < self.dist[pos] {
                self.dist.swap(parent, pos);
                self.fraud.swap(parent, pos);
                pos = parent;
            } else { break; }
        }
    }
    fn sift_down(&mut self, mut pos: usize) {
        loop {
            let left = 2 * pos + 1;
            let right = 2 * pos + 2;
            let mut largest = pos;
            if left < self.count && self.dist[left] > self.dist[largest] { largest = left; }
            if right < self.count && self.dist[right] > self.dist[largest] { largest = right; }
            if largest == pos { break; }
            self.dist.swap(pos, largest);
            self.fraud.swap(pos, largest);
            pos = largest;
        }
    }
    fn fraud_count(&self) -> u8 {
        self.fraud[..self.count].iter().sum()
    }
}

// ---------- SIMD: AABB lower-bound for one cluster (16 padded dims) ----------

#[target_feature(enable = "avx2")]
unsafe fn aabb_lb_one(q_pad: *const i16, min_pad: *const i16, max_pad: *const i16) -> i64 {
    use std::arch::x86_64::*;
    let qvec = _mm256_loadu_si256(q_pad as *const __m256i);
    let bmin = _mm256_loadu_si256(min_pad as *const __m256i);
    let bmax = _mm256_loadu_si256(max_pad as *const __m256i);
    let zero = _mm256_setzero_si256();
    let below = _mm256_max_epi16(_mm256_sub_epi16(bmin, qvec), zero);
    let above = _mm256_max_epi16(_mm256_sub_epi16(qvec, bmax), zero);
    let gap = _mm256_max_epi16(below, above);
    let sq = _mm256_madd_epi16(gap, gap); // 8×i32
    // hsum 8 i32 → i64
    let lo = _mm256_cvtepi32_epi64(_mm256_castsi256_si128(sq));
    let hi = _mm256_cvtepi32_epi64(_mm256_extracti128_si256(sq, 1));
    let s = _mm256_add_epi64(lo, hi); // 4×i64
    let s128 = _mm_add_epi64(
        _mm256_castsi256_si128(s),
        _mm256_extracti128_si256(s, 1),
    );
    _mm_extract_epi64(s128, 0) + _mm_extract_epi64(s128, 1)
}

// ---------- SIMD: 8-vec L2² with disc-pair early exit ----------

#[target_feature(enable = "avx2")]
unsafe fn scan_block_avx2(
    qpairs: *const std::arch::x86_64::__m256i,
    block_ptr: *const i16,
    worst: i64,
    full: bool,
) -> Option<[i64; BLOCK]> {
    use std::arch::x86_64::*;
    // Pair 0 = disc dims (placed first at build time)
    let v0 = _mm256_loadu_si256(block_ptr as *const __m256i);
    let d0 = _mm256_sub_epi16(v0, _mm256_loadu_si256(qpairs));
    let p0 = _mm256_madd_epi16(d0, d0); // 8 i32, max ≈ 8e8

    // Early exit: if partial > worst on all 8 lanes, skip block.
    if full && worst >= 0 && worst <= i32::MAX as i64 {
        let cmp = _mm256_cmpgt_epi32(_mm256_set1_epi32(worst as i32), p0);
        if _mm256_testz_si256(cmp, cmp) != 0 { return None; }
    }

    // Group remaining 6 pairs into (1,2), (3,4), (5,6) sums (i32 safe: max 1.6e9 each).
    let pair_load = |p: usize| -> __m256i {
        _mm256_loadu_si256(block_ptr.add(p * 16) as *const __m256i)
    };
    let pair_q = |p: usize| -> __m256i {
        _mm256_loadu_si256(qpairs.add(p))
    };
    let madd_pair = |p: usize| -> __m256i {
        let v = pair_load(p);
        let d = _mm256_sub_epi16(v, pair_q(p));
        _mm256_madd_epi16(d, d)
    };

    let g0 = _mm256_add_epi32(p0, madd_pair(1));        // pairs 0+1
    let g1 = _mm256_add_epi32(madd_pair(2), madd_pair(3));
    let g2 = _mm256_add_epi32(madd_pair(4), madd_pair(5));
    let g3 = madd_pair(6);

    // Sum 4 i32 groups into i64.
    let widen = |x: __m256i| -> (__m256i, __m256i) {
        (
            _mm256_cvtepi32_epi64(_mm256_castsi256_si128(x)),
            _mm256_cvtepi32_epi64(_mm256_extracti128_si256(x, 1)),
        )
    };
    let (g0_lo, g0_hi) = widen(g0);
    let (g1_lo, g1_hi) = widen(g1);
    let (g2_lo, g2_hi) = widen(g2);
    let (g3_lo, g3_hi) = widen(g3);
    let acc_lo = _mm256_add_epi64(
        _mm256_add_epi64(g0_lo, g1_lo),
        _mm256_add_epi64(g2_lo, g3_lo),
    );
    let acc_hi = _mm256_add_epi64(
        _mm256_add_epi64(g0_hi, g1_hi),
        _mm256_add_epi64(g2_hi, g3_hi),
    );

    let mut out = [0i64; BLOCK];
    _mm256_storeu_si256(out.as_mut_ptr() as *mut __m256i, acc_lo);
    _mm256_storeu_si256(out[4..].as_mut_ptr() as *mut __m256i, acc_hi);
    Some(out)
}

// ---------- mmap RAII ----------

struct Mmap {
    ptr: *const u8,
    len: usize,
}

unsafe impl Send for Mmap {}
unsafe impl Sync for Mmap {}

impl Mmap {
    fn open(path: &str) -> Self {
        unsafe {
            let cpath = CString::new(path).expect("bad path");
            let fd = libc::open(cpath.as_ptr(), libc::O_RDONLY);
            if fd < 0 { panic!("open {} failed", path); }
            let mut st: libc::stat = std::mem::zeroed();
            if libc::fstat(fd, &mut st) != 0 { panic!("fstat failed"); }
            let len = st.st_size as usize;
            let p = libc::mmap(
                std::ptr::null_mut(),
                len,
                libc::PROT_READ,
                libc::MAP_PRIVATE | libc::MAP_POPULATE,
                fd,
                0,
            );
            if p == libc::MAP_FAILED { panic!("mmap failed"); }
            libc::close(fd);
            if libc::mlock(p, len) != 0 {
                eprintln!("[ivf] mlock failed errno={} (continuing)", *libc::__errno_location());
            }
            let _ = libc::madvise(p, len, libc::MADV_HUGEPAGE);
            let _ = libc::madvise(p, len, libc::MADV_WILLNEED);
            Mmap { ptr: p as *const u8, len }
        }
    }
}

// ---------- Thread-local scratch (single-threaded server) ----------

struct ScratchCell(UnsafeCell<[u64; NUM_CLUSTERS]>);
unsafe impl Sync for ScratchCell {}
static SCRATCH: ScratchCell = ScratchCell(UnsafeCell::new([0u64; NUM_CLUSTERS]));

// ---------- IvfIndex ----------

pub struct IvfIndex {
    _mmap: Mmap,
    n_clusters: usize,
    #[allow(dead_code)]
    n_blocks: usize,
    pair_dims: [u8; DIMS],          // pair_dims[2*p..2*p+2] = dims in pair p; pair 0 = disc
    aabb_min_pad: *const i16,       // n_clusters × 16 × i16
    aabb_max_pad: *const i16,
    cluster_meta: *const u64,       // n_clusters × u64 (start_block<<32 | num_blocks)
    block_labels: *const u8,
    block_counts: *const u8,
    pair_blocks: *const i16,        // n_blocks × 7 × 16 × i16
}

unsafe impl Send for IvfIndex {}
unsafe impl Sync for IvfIndex {}

impl IvfIndex {
    pub fn build(path: &str) -> BuiltIndex {
        eprintln!("[ivf] loading {}...", path);
        let file = std::fs::File::open(path).expect("failed to open dataset");
        let gz = GzDecoder::new(file);
        let entries: Vec<RefEntry> = serde_json::from_reader(gz).expect("failed to parse dataset");
        let n = entries.len();
        eprintln!("[ivf] loaded {} vectors", n);

        let mut raw_vecs: Vec<[i16; DIMS]> = Vec::with_capacity(n);
        let mut raw_labels: Vec<u64> = vec![0u64; (n + 63) / 64];

        for (i, e) in entries.iter().enumerate() {
            raw_vecs.push(quantize_vec(&e.vector));
            if e.label == "fraud" {
                raw_labels[i / 64] |= 1u64 << (i % 64);
            }
        }
        drop(entries);

        // Discriminative dims: top-2 by sum of squares (variance proxy)
        let mut sum_sq = [0i64; DIMS];
        for v in &raw_vecs {
            for d in 0..DIMS {
                sum_sq[d] += v[d] as i64 * v[d] as i64;
            }
        }
        let mut var_order: Vec<(i64, usize)> = sum_sq.iter().enumerate()
            .map(|(d, &s)| (s, d)).collect();
        var_order.sort_unstable_by(|a, b| b.0.cmp(&a.0));
        let disc_a = var_order[0].1;
        let disc_b = var_order[1].1;

        // pair_dims[0..2] = disc pair, pair_dims[2..] = remaining 12 in original order, paired
        let mut pair_dims = [0u8; DIMS];
        pair_dims[0] = disc_a as u8;
        pair_dims[1] = disc_b as u8;
        let mut wi = 2;
        for d in 0..DIMS {
            if d != disc_a && d != disc_b {
                pair_dims[wi] = d as u8;
                wi += 1;
            }
        }

        eprintln!("[ivf] k-means C={} iters={}...", NUM_CLUSTERS, KMEANS_ITERS);
        let centroids_f32 = kmeans(&raw_vecs, NUM_CLUSTERS, KMEANS_ITERS);
        let centroids: Vec<[i16; DIMS]> = centroids_f32.iter()
            .map(|c| c.map(|x| (x * SCALE).round().clamp(-SCALE, SCALE) as i16))
            .collect();

        eprintln!("[ivf] assigning vectors...");
        let assignments = assign_all(&raw_vecs, &centroids);

        let mut order: Vec<u32> = (0..n as u32).collect();
        order.sort_unstable_by_key(|&i| assignments[i as usize]);

        let mut cluster_start = vec![0u32; NUM_CLUSTERS];
        let mut cluster_len = vec![0u32; NUM_CLUSTERS];
        {
            let mut c = 0usize;
            let mut start = 0usize;
            for i in 0..n {
                let a = assignments[order[i] as usize];
                while c < a {
                    cluster_len[c] = (i - start) as u32;
                    c += 1;
                    start = i;
                    cluster_start[c] = i as u32;
                }
            }
            cluster_len[c] = (n - start) as u32;
        }

        // AABB padded to 16 dims (last 2 = 0)
        let mut aabb_min_pad = vec![[0i16; DIMS_PAD]; NUM_CLUSTERS];
        let mut aabb_max_pad = vec![[0i16; DIMS_PAD]; NUM_CLUSTERS];
        for c in 0..NUM_CLUSTERS {
            let s = cluster_start[c] as usize;
            let e = s + cluster_len[c] as usize;
            if s == e { continue; }
            for d in 0..DIMS {
                aabb_min_pad[c][d] = i16::MAX;
                aabb_max_pad[c][d] = i16::MIN;
            }
            for i in s..e {
                let v = &raw_vecs[order[i] as usize];
                for d in 0..DIMS {
                    if v[d] < aabb_min_pad[c][d] { aabb_min_pad[c][d] = v[d]; }
                    if v[d] > aabb_max_pad[c][d] { aabb_max_pad[c][d] = v[d]; }
                }
            }
            // padded dims 14, 15 stay 0 (q's padded also 0, gap=0, no contribution)
        }

        eprintln!("[ivf] packing pair blocks...");
        let n_blocks: usize = (0..NUM_CLUSTERS).map(|c| {
            let l = cluster_len[c] as usize;
            (l + BLOCK - 1) / BLOCK
        }).sum();

        let mut pair_blocks: Vec<i16> = vec![0i16; n_blocks * PAIRS * 16];
        let mut block_labels: Vec<u8> = Vec::with_capacity(n_blocks);
        let mut block_counts: Vec<u8> = Vec::with_capacity(n_blocks);
        let mut cluster_meta: Vec<u64> = vec![0u64; NUM_CLUSTERS];

        let mut bi: usize = 0;
        for c in 0..NUM_CLUSTERS {
            let s = cluster_start[c] as usize;
            let e = s + cluster_len[c] as usize;
            let start_block = bi;
            let mut b = s;
            while b < e {
                let be = (b + BLOCK).min(e);
                let count = be - b;
                let mut lbl = 0u8;
                for v in 0..count {
                    let orig_idx = order[b + v] as usize;
                    let vec = &raw_vecs[orig_idx];
                    for p in 0..PAIRS {
                        let da = pair_dims[2 * p] as usize;
                        let db = pair_dims[2 * p + 1] as usize;
                        let off = bi * PAIRS * 16 + p * 16 + v * 2;
                        pair_blocks[off] = vec[da];
                        pair_blocks[off + 1] = vec[db];
                    }
                    let is_fraud = (raw_labels[orig_idx / 64] >> (orig_idx % 64)) & 1;
                    lbl |= (is_fraud as u8) << v;
                }
                // padded vectors v=count..8: leave 0; query loop filters via cnt
                block_labels.push(lbl);
                block_counts.push(count as u8);
                bi += 1;
                b += BLOCK;
            }
            let num_blocks = (bi - start_block) as u64;
            cluster_meta[c] = ((start_block as u64) << 32) | num_blocks;
        }
        assert_eq!(bi, n_blocks);

        eprintln!("[ivf] built {} blocks, disc=({},{})", n_blocks, disc_a, disc_b);
        BuiltIndex {
            pair_dims,
            aabb_min_pad,
            aabb_max_pad,
            cluster_meta,
            block_labels,
            block_counts,
            pair_blocks,
        }
    }

    pub fn load(path: &str) -> Self {
        let mmap = Mmap::open(path);
        unsafe {
            let base = mmap.ptr;
            let mut off = 0usize;

            // header: 8 magic + 8 n_clusters + 8 n_blocks + 14 pair_dims + 2 pad = 40 bytes
            let magic = std::slice::from_raw_parts(base, 8);
            assert_eq!(magic, MAGIC, "bad magic — rebuild index");
            off += 8;
            let n_clusters = *(base.add(off) as *const u64) as usize;
            off += 8;
            let n_blocks = *(base.add(off) as *const u64) as usize;
            off += 8;
            let mut pair_dims = [0u8; DIMS];
            std::ptr::copy_nonoverlapping(base.add(off), pair_dims.as_mut_ptr(), DIMS);
            off += DIMS + 2; // +2 pad to align to 8 (40 total)

            let aabb_min_pad = base.add(off) as *const i16;
            off += n_clusters * DIMS_PAD * 2;
            let aabb_max_pad = base.add(off) as *const i16;
            off += n_clusters * DIMS_PAD * 2;
            // align off to 8 for u64
            off = (off + 7) & !7;
            let cluster_meta = base.add(off) as *const u64;
            off += n_clusters * 8;
            let block_labels = base.add(off);
            off += n_blocks;
            let block_counts = base.add(off);
            off += n_blocks;
            // align to 2 for i16
            off = (off + 1) & !1;
            let pair_blocks = base.add(off) as *const i16;
            off += n_blocks * PAIRS * 16 * 2;
            assert!(off <= mmap.len, "index truncated: off={} len={}", off, mmap.len);

            eprintln!("[ivf] mmap loaded ({} clusters, {} blocks, {} bytes)",
                n_clusters, n_blocks, mmap.len);
            IvfIndex {
                _mmap: mmap,
                n_clusters,
                n_blocks,
                pair_dims,
                aabb_min_pad,
                aabb_max_pad,
                cluster_meta,
                block_labels,
                block_counts,
                pair_blocks,
            }
        }
    }

    #[inline(always)]
    pub fn query(&self, q: &[i16; DIMS]) -> u8 {
        // Pad query to 16
        let mut q_pad = [0i16; DIMS_PAD];
        q_pad[..DIMS].copy_from_slice(q);

        // Pre-broadcast per-pair query
        let mut qpairs = [unsafe { std::arch::x86_64::_mm256_setzero_si256() }; PAIRS];
        unsafe {
            for p in 0..PAIRS {
                let da = self.pair_dims[2 * p] as usize;
                let db = self.pair_dims[2 * p + 1] as usize;
                let packed = (q[da] as u16 as u32) | ((q[db] as u16 as u32) << 16);
                qpairs[p] = std::arch::x86_64::_mm256_set1_epi32(packed as i32);
            }
        }

        // Compute AABB LB for all clusters → packed (lb<<12 | c)
        let scratch: &mut [u64; NUM_CLUSTERS] = unsafe { &mut *SCRATCH.0.get() };
        unsafe {
            for c in 0..self.n_clusters {
                let lb = aabb_lb_one(
                    q_pad.as_ptr(),
                    self.aabb_min_pad.add(c * DIMS_PAD),
                    self.aabb_max_pad.add(c * DIMS_PAD),
                );
                // pack: lb (52 bits) << 12 | c (12 bits)
                let lb_u = (lb as u64) & 0x000F_FFFF_FFFF_FFFF;
                scratch[c] = (lb_u << 12) | (c as u64);
            }
        }

        // Partial sort: select top FULL_NPROBE smallest (fast pass also drawn from this).
        let probe_cap = FULL_NPROBE.min(self.n_clusters);
        scratch[..self.n_clusters].select_nth_unstable(probe_cap - 1);
        let top = &mut scratch[..probe_cap];
        top.sort_unstable();

        let mut top5 = Top5::new();

        // FAST pass: first FAST_NPROBE clusters
        let fast = FAST_NPROBE.min(probe_cap);
        for pi in 0..fast {
            let packed = top[pi];
            let c = (packed & 0xFFF) as usize;
            let lb = (packed >> 12) as i64;
            if top5.full() && lb >= top5.worst() { continue; }
            self.probe_cluster(c, &qpairs, &mut top5);
        }

        // Decide escalation
        let count = top5.fraud_count() as usize;
        let needs_full = top5.full()
            && top5.worst() >= FAST_T[count];

        if needs_full {
            for pi in fast..probe_cap {
                let packed = top[pi];
                let c = (packed & 0xFFF) as usize;
                let lb = (packed >> 12) as i64;
                if top5.full() && lb >= top5.worst() { break; }
                self.probe_cluster(c, &qpairs, &mut top5);
            }
        }

        top5.fraud_count()
    }

    /// Single-pass query with a custom nprobe. Returns (fraud_count, worst_dist).
    /// Used by bin/tune to derive FAST_T thresholds offline.
    pub fn query_probe(&self, q: &[i16; DIMS], nprobe: usize) -> (u8, i64) {
        let mut q_pad = [0i16; DIMS_PAD];
        q_pad[..DIMS].copy_from_slice(q);
        let mut qpairs = [unsafe { std::arch::x86_64::_mm256_setzero_si256() }; PAIRS];
        unsafe {
            for p in 0..PAIRS {
                let da = self.pair_dims[2 * p] as usize;
                let db = self.pair_dims[2 * p + 1] as usize;
                let packed = (q[da] as u16 as u32) | ((q[db] as u16 as u32) << 16);
                qpairs[p] = std::arch::x86_64::_mm256_set1_epi32(packed as i32);
            }
        }
        let scratch: &mut [u64; NUM_CLUSTERS] = unsafe { &mut *SCRATCH.0.get() };
        unsafe {
            for c in 0..self.n_clusters {
                let lb = aabb_lb_one(
                    q_pad.as_ptr(),
                    self.aabb_min_pad.add(c * DIMS_PAD),
                    self.aabb_max_pad.add(c * DIMS_PAD),
                );
                let lb_u = (lb as u64) & 0x000F_FFFF_FFFF_FFFF;
                scratch[c] = (lb_u << 12) | (c as u64);
            }
        }
        let probe_cap = nprobe.min(self.n_clusters);
        scratch[..self.n_clusters].select_nth_unstable(probe_cap - 1);
        let top = &mut scratch[..probe_cap];
        top.sort_unstable();

        let mut top5 = Top5::new();
        for pi in 0..probe_cap {
            let packed = top[pi];
            let c = (packed & 0xFFF) as usize;
            let lb = (packed >> 12) as i64;
            if top5.full() && lb >= top5.worst() { break; }
            self.probe_cluster(c, &qpairs, &mut top5);
        }
        (top5.fraud_count(), if top5.full() { top5.worst() } else { i64::MAX })
    }

    #[inline(always)]
    fn probe_cluster(
        &self,
        c: usize,
        qpairs: &[std::arch::x86_64::__m256i; PAIRS],
        top5: &mut Top5,
    ) {
        let meta = unsafe { *self.cluster_meta.add(c) };
        let sb = (meta >> 32) as usize;
        let nb = (meta & 0xFFFF_FFFF) as usize;
        unsafe {
            for bi in sb..sb + nb {
                let block_ptr = self.pair_blocks.add(bi * PAIRS * 16);
                // prefetch next block
                if bi + 1 < sb + nb {
                    std::arch::x86_64::_mm_prefetch(
                        self.pair_blocks.add((bi + 1) * PAIRS * 16) as *const i8,
                        std::arch::x86_64::_MM_HINT_T0,
                    );
                }
                let cnt = *self.block_counts.add(bi) as usize;
                let lbl = *self.block_labels.add(bi);
                let worst = if top5.full() { top5.worst() } else { i64::MAX };
                let full = top5.full();
                if let Some(dists) = scan_block_avx2(
                    qpairs.as_ptr(),
                    block_ptr,
                    worst,
                    full,
                ) {
                    for v in 0..cnt {
                        if !top5.full() || dists[v] < top5.worst() {
                            top5.push(dists[v], (lbl >> v) & 1);
                        }
                    }
                }
            }
        }
    }
}

// ---------- Builder-owned heap form, separate from mmap-backed runtime form ----------

pub struct BuiltIndex {
    pair_dims: [u8; DIMS],
    aabb_min_pad: Vec<[i16; DIMS_PAD]>,
    aabb_max_pad: Vec<[i16; DIMS_PAD]>,
    cluster_meta: Vec<u64>,
    block_labels: Vec<u8>,
    block_counts: Vec<u8>,
    pair_blocks: Vec<i16>,
}

impl BuiltIndex {
    pub fn save(&self, path: &str) {
        use std::io::Write;
        let n_clusters = self.aabb_min_pad.len() as u64;
        let n_blocks = self.block_counts.len() as u64;

        let mut f = std::io::BufWriter::new(
            std::fs::File::create(path).expect("create index file"),
        );

        // header (40 bytes): magic(8) + n_clusters(8) + n_blocks(8) + pair_dims(14) + pad(2)
        f.write_all(MAGIC).unwrap();
        f.write_all(&n_clusters.to_le_bytes()).unwrap();
        f.write_all(&n_blocks.to_le_bytes()).unwrap();
        f.write_all(&self.pair_dims).unwrap();
        f.write_all(&[0u8; 2]).unwrap();

        // aabb_min_pad, aabb_max_pad
        f.write_all(bytes_of_slice(&self.aabb_min_pad)).unwrap();
        f.write_all(bytes_of_slice(&self.aabb_max_pad)).unwrap();

        // align to 8 (cluster_meta is u64) — already aligned: 40 + 2*n*32 always 8-aligned
        f.write_all(bytes_of_slice(&self.cluster_meta)).unwrap();

        f.write_all(&self.block_labels).unwrap();
        f.write_all(&self.block_counts).unwrap();

        // align to 2 (i16): n_blocks*2 bytes after labels+counts → may need 1 byte pad
        let after_labels = self.block_labels.len() + self.block_counts.len();
        if after_labels & 1 == 1 {
            f.write_all(&[0u8]).unwrap();
        }

        f.write_all(bytes_of_slice(&self.pair_blocks)).unwrap();

        let total = 40
            + (self.aabb_min_pad.len() + self.aabb_max_pad.len()) * DIMS_PAD * 2
            + self.cluster_meta.len() * 8
            + self.block_labels.len() + self.block_counts.len()
            + (after_labels & 1)
            + self.pair_blocks.len() * 2;
        eprintln!("[ivf] saved index ({} blocks, {} bytes)", n_blocks, total);
    }
}

fn bytes_of_slice<T: Copy>(v: &[T]) -> &[u8] {
    unsafe { std::slice::from_raw_parts(v.as_ptr() as *const u8, std::mem::size_of_val(v)) }
}

// ---------- K-means (builder only) ----------

fn kmeans(vecs: &[[i16; DIMS]], c: usize, iters: usize) -> Vec<[f32; DIMS]> {
    let n = vecs.len();
    let stride = n / c;
    let mut centroids: Vec<[f32; DIMS]> = (0..c)
        .map(|i| vecs[i * stride].map(|x| x as f32 / SCALE))
        .collect();
    let mut assignments = vec![0usize; n];

    for iter in 0..iters {
        let cen_i16: Vec<[i16; DIMS]> = centroids.iter()
            .map(|c| c.map(|x| (x * SCALE).round().clamp(-SCALE, SCALE) as i16))
            .collect();

        let mut changed = 0usize;
        for i in 0..n {
            let best = (0..c).min_by_key(|&j| l2sq_i16(&vecs[i], &cen_i16[j])).unwrap();
            if best != assignments[i] { changed += 1; }
            assignments[i] = best;
        }

        let mut sums = vec![[0i64; DIMS]; c];
        let mut counts = vec![0usize; c];
        for i in 0..n {
            let ci = assignments[i];
            for d in 0..DIMS { sums[ci][d] += vecs[i][d] as i64; }
            counts[ci] += 1;
        }
        for ci in 0..c {
            if counts[ci] > 0 {
                for d in 0..DIMS {
                    centroids[ci][d] = sums[ci][d] as f32 / (counts[ci] as f32 * SCALE);
                }
            }
        }

        eprintln!("[kmeans] iter {}/{} changed={}", iter + 1, iters, changed);
        if changed == 0 { break; }
    }
    centroids
}

fn assign_all(vecs: &[[i16; DIMS]], centroids: &[[i16; DIMS]]) -> Vec<usize> {
    vecs.iter()
        .map(|v| {
            (0..centroids.len())
                .min_by_key(|&j| l2sq_i16(v, &centroids[j]))
                .unwrap_or(0)
        })
        .collect()
}
